version: '3.8'
services:
  mysql:
    container_name: legal-one-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=legal-one
      - MYSQL_DATABASE=legal-one
      - MYSQL_PASSWORD=legal-one
      - MYSQL_USER=legal-one
    ports:
      - '4306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
  php:
    container_name: legal-one-php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
  nginx:
    container_name: legal-one-nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql